#!/bin/bash

# R parameters

CONFIG_ID="$1"

INSTANCE_ID="$2"

SEED="$3"

INSTANCE="${4}"

ELITE_SIZE="-e ${5}"

MUTANTS="-m ${6}"

POPULATION_SIZE="-p ${7}"

EXE="../BRKGA.jl"

JL_PROJECT="/home/lucas.guilhon/IND2602/p-dispersion/BRKGA"

/home/lucas.guilhon/julia-1.9.3/bin/julia --project=${JL_PROJECT} ${EXE} -i ${INSTANCE} ${ELITE_SIZE} ${MUTANTS} ${POPULATION_SIZE} | tail -n 1

